LOAD DATA
INFILE '$MYPROJECTHOME/projetMBDS/SQLLOADER/Clients_8.csv'
INSERT INTO TABLE client_8
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
AGE,
SEXE,
TAUX,
SITUATIONFAMILIALE,
NBENFANTSACHARGE,
XVOITURE,
IMMATRICULATION
)
